### ISSUE TITLE
AttributeError: 'Saml2Client' object has no attribute 'want_assertions_or_response_signed

### ISSUE THREAD

**Issue by jerryz1982** [IdentityPython/pysaml2#575]
parse_authn_request_response of saml2client returns exception after upgrading to 4.6.4

## Code Version
4.6.4

## Expected Behavior
parse_authn_request_response returns no exception

## Current Behavior
AttributeError: 'Saml2Client' object has no attribute 'want_assertions_or_response_signed

## Possible Solution
give want_assertions_or_response_signed default value when it is not set in config.

## Steps to Reproduce
1. upgrade to 4.6.4
2. create client instance without want_assertions_or_response_signed being set
3. saml_client.parse_authn_request_response(
                flask.request.form['SAMLResponse'],
                saml2.entity.BINDING_HTTP_POST,
            )

**Comment by jerryz1982** [comment]
issue was caused by old client instance in memory cache. reset cache fixed it.
